// Code generated by hack/gentestdb, DO NOT EDIT.

package database

// Copyright (c) Microsoft Corporation.
// Licensed under the Apache License 2.0.

import (
	"bytes"
	"context"
	"errors"
	"net/http"
	"sync"
	"time"

	"github.com/ugorji/go/codec"

	"github.com/Azure/ARO-RP/pkg/api"
	"github.com/Azure/ARO-RP/pkg/database/cosmosdb"
)

type fakeSubscriptions struct {
	docs       map[string]*string
	jsonHandle *codec.JsonHandle
	lock       sync.Locker
}

func newSubscriptions(h *codec.JsonHandle) *fakeSubscriptions {
	return &fakeSubscriptions{
		docs:       make(map[string]*string),
		jsonHandle: h,
		lock:       &sync.Mutex{},
	}
}

func (c *fakeSubscriptions) fromString(s *string) (*api.SubscriptionDocument, error) {

	res := &api.SubscriptionDocument{}
	d := codec.NewDecoder(bytes.NewBufferString(*s), c.jsonHandle)
	err := d.Decode(&res)

	return res, err

}

func (c *fakeSubscriptions) Create(ctx context.Context, partitionkey string, doc *api.SubscriptionDocument, options *cosmosdb.Options) (*api.SubscriptionDocument, error) {
	c.lock.Lock()
	defer c.lock.Unlock()

	var err error

	_, ext := c.docs[doc.ID]
	if ext {
		// it's here
		return nil, errors.New("sdkjfbg")
	}

	buf := &bytes.Buffer{}
	err = codec.NewEncoder(buf, c.jsonHandle).Encode(doc)
	if err != nil {
		return nil, err
	}

	out := buf.String()
	c.docs[doc.ID] = &out

	return c.fromString(&out)

}
func (c *fakeSubscriptions) List(*cosmosdb.Options) cosmosdb.SubscriptionDocumentRawIterator {
	return nil
}
func (c *fakeSubscriptions) ListAll(context.Context, *cosmosdb.Options) (*api.SubscriptionDocuments, error) {
	return nil, errors.New("not implemented")
}
func (c *fakeSubscriptions) Get(ctx context.Context, partitionkey string, documentId string, options *cosmosdb.Options) (*api.SubscriptionDocument, error) {
	c.lock.Lock()
	defer c.lock.Unlock()
	out, ext := c.docs[documentId]

	if !ext {
		return nil, &cosmosdb.Error{StatusCode: http.StatusNotFound}
	}

	dec, err := c.fromString(out)
	if err != nil {
		return nil, err
	}

	return dec, err

}
func (c *fakeSubscriptions) Replace(ctx context.Context, partitionkey string, doc *api.SubscriptionDocument, options *cosmosdb.Options) (*api.SubscriptionDocument, error) {
	c.lock.Lock()
	defer c.lock.Unlock()

	_, ext := c.docs[doc.ID]
	if !ext {
		// it's here
		return nil, errors.New("does not exist")
	}

	if options != nil {
		for _, o := range options.PreTriggers {
			if o == "renewLease" {
				doc.LeaseExpires = int(time.Now().Unix()) + 60
			}
		}
	}

	buf := &bytes.Buffer{}
	err := codec.NewEncoder(buf, c.jsonHandle).Encode(doc)
	if err != nil {
		return nil, err
	}

	out := buf.String()
	c.docs[doc.ID] = &out

	return c.fromString(&out)

}

func (c *fakeSubscriptions) Delete(ctx context.Context, partitionKey string, doc *api.SubscriptionDocument, options *cosmosdb.Options) error {
	c.lock.Lock()
	defer c.lock.Unlock()

	_, ext := c.docs[doc.ID]
	if !ext {
		return errors.New("does not exist")
	}

	delete(c.docs, doc.ID)

	return nil
}

func (c *fakeSubscriptions) Query(name string, query *cosmosdb.Query, options *cosmosdb.Options) cosmosdb.SubscriptionDocumentRawIterator {
	return nil
}
func (c *fakeSubscriptions) QueryAll(ctx context.Context, partitionkey string, query *cosmosdb.Query, options *cosmosdb.Options) (*api.SubscriptionDocuments, error) {
	return nil, errors.New("not implemented but for get")
}

func (c *fakeSubscriptions) ChangeFeed(*cosmosdb.Options) cosmosdb.SubscriptionDocumentIterator {
	return nil
}

type fakeSubscriptionsRawIterator struct {
	docs []*api.SubscriptionDocument
}

func (i *fakeSubscriptionsRawIterator) Next(ctx context.Context, maxItemCount int) (*api.SubscriptionDocuments, error) {
	docs := &api.SubscriptionDocuments{}
	err := i.NextRaw(ctx, maxItemCount, docs)
	return docs, err
}

func (i *fakeSubscriptionsRawIterator) NextRaw(ctx context.Context, maxItemCount int, raw interface{}) error {
	if maxItemCount == -1 {
		d := raw.(*api.SubscriptionDocuments)
		d.Count = len(i.docs)
		d.SubscriptionDocuments = i.docs
		return nil
	} else {
		return errors.New("not implemented")
	}
}

func (i *fakeSubscriptionsRawIterator) Continuation() string {
	return ""
}
