// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Azure/ARO-RP/pkg/util/azureclient/mgmt/keyvault (interfaces: VaultsClient)

// Package mock_keyvault is a generated GoMock package.
package mock_keyvault

import (
	context "context"
	reflect "reflect"

	keyvault "github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2016-10-01/keyvault"
	gomock "github.com/golang/mock/gomock"
)

// MockVaultsClient is a mock of VaultsClient interface
type MockVaultsClient struct {
	ctrl     *gomock.Controller
	recorder *MockVaultsClientMockRecorder
}

// MockVaultsClientMockRecorder is the mock recorder for MockVaultsClient
type MockVaultsClientMockRecorder struct {
	mock *MockVaultsClient
}

// NewMockVaultsClient creates a new mock instance
func NewMockVaultsClient(ctrl *gomock.Controller) *MockVaultsClient {
	mock := &MockVaultsClient{ctrl: ctrl}
	mock.recorder = &MockVaultsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVaultsClient) EXPECT() *MockVaultsClientMockRecorder {
	return m.recorder
}

// ListByResourceGroup mocks base method
func (m *MockVaultsClient) ListByResourceGroup(arg0 context.Context, arg1 string, arg2 *int32) ([]keyvault.Vault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByResourceGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].([]keyvault.Vault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByResourceGroup indicates an expected call of ListByResourceGroup
func (mr *MockVaultsClientMockRecorder) ListByResourceGroup(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByResourceGroup", reflect.TypeOf((*MockVaultsClient)(nil).ListByResourceGroup), arg0, arg1, arg2)
}
