// Copyright (c) Microsoft Corporation.
// Licensed under the Apache License 2.0.

// Code generated by client-gen-v0.25.16. DO NOT EDIT.

// This package has the automatically generated clientset.
package versioned
