#!/bin/bash

git rm pkg/util/arm/deploy.go
git rm pkg/util/arm/deploy_test.go
git rm vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credential.go
git rm vendor/github.com/aliyun/alibaba-cloud-sdk-go/sdk/errors/error.go
git rm vendor/github.com/chai2010/gettext-go/LICENSE
git rm vendor/github.com/golangci/golangci-lint/pkg/config/linters_settings_gocritic.go
git rm vendor/github.com/jgautheron/goconst/README.md
git rm vendor/github.com/metal3-io/baremetal-operator/pkg/hardwareutils/bmc/idrac.go
git rm vendor/github.com/mgechev/dots/resolve.go
git rm vendor/github.com/mgechev/revive/rule/cyclomatic.go
git rm vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
git rm vendor/github.com/openshift/client-go/machine/clientset/versioned/clientset.go
git rm vendor/github.com/openshift/client-go/machine/clientset/versioned/fake/register.go
git rm vendor/github.com/openshift/client-go/machine/clientset/versioned/scheme/register.go
git rm vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machine_client.go
git rm vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machine_client.go
git rm vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/common_types.go
git rm vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/doc.go
git rm vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
git rm vendor/github.com/openshift/installer/pkg/asset/ignition/bootstrap/bootstrap_ignition.go
git rm vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
git rm vendor/github.com/quasilyte/go-ruleguard/internal/gogrep/parse.go
git rm vendor/github.com/tommy-muehle/go-mnd/v2/.editorconfig
git rm vendor/github.com/tommy-muehle/go-mnd/v2/.gitignore
git rm vendor/github.com/tommy-muehle/go-mnd/v2/analyzer.go
git rm vendor/github.com/tommy-muehle/go-mnd/v2/checks/argument.go
git rm vendor/github.com/tommy-muehle/go-mnd/v2/checks/assign.go
git rm vendor/github.com/tommy-muehle/go-mnd/v2/checks/operation.go
git rm vendor/github.com/tommy-muehle/go-mnd/v2/checks/return.go
git rm vendor/github.com/tommy-muehle/go-mnd/v2/config/config.go
git rm vendor/honnef.co/go/tools/analysis/code/code.go
git rm vendor/honnef.co/go/tools/analysis/code/visit.go
git rm vendor/honnef.co/go/tools/analysis/facts/deprecated.go
git rm vendor/honnef.co/go/tools/analysis/report/report.go
git rm vendor/honnef.co/go/tools/go/ir/doc.go
git rm vendor/honnef.co/go/tools/go/ir/exits.go
git rm vendor/honnef.co/go/tools/go/ir/html.go
git rm vendor/honnef.co/go/tools/go/ir/irutil/load.go
git rm vendor/honnef.co/go/tools/go/ir/irutil/visit.go
git rm vendor/honnef.co/go/tools/go/ir/util.go
git rm vendor/honnef.co/go/tools/knowledge/arg.go
git rm vendor/k8s.io/api/flowcontrol/v1beta2/doc.go
git rm vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
git rm vendor/k8s.io/client-go/applyconfigurations/core/v1/lifecyclehandler.go
git rm vendor/sigs.k8s.io/kustomize/api/filters/prefix/prefix.go