FROM mcr.microsoft.com/azurelinux/base/python:3.12 AS builder

RUN python3 -m venv /data/venv
RUN /data/venv/bin/pip install pytest azdev azure-cli==2.78.0
COPY /python /data/

WORKDIR /data/az/aro
RUN /data/venv/bin/pytest --ignore=azext_aro/tests/latest/integration
RUN /data/venv/bin/python3 setup.py bdist_wheel

FROM mcr.microsoft.com/azure-cli:2.82.0 AS final
COPY --from=builder /data/az/aro/dist /opt/az
RUN az extension add --yes --source /opt/az/aro-*-py2.py3-none-any.whl
