# Uses a multi-stage container build to build the proxy
#
ARG REGISTRY
FROM mcr.microsoft.com/oss/go/microsoft/golang:1.23-fips-cbl-mariner2.0 AS builder
USER root
ENV GOPATH=/root/go CGO_ENABLED=1 GOFLAGS='-tags=requirefips'
RUN mkdir -p /app
WORKDIR /app

COPY . /app
RUN make proxy

FROM ${REGISTRY}/ubi8/ubi-minimal
RUN microdnf update && microdnf clean all
COPY --from=builder /app/proxy /usr/local/bin/
ENTRYPOINT ["proxy"]
EXPOSE 8443/tcp
EXPOSE 8080/tcp
USER 1000
