# Uses a multi-stage container build to build the proxy
#
ARG BUILDER_REGISTRY
ARG BUILDER_REPOSITORY=openshift-release-dev/golang-builder--partner-share
ARG BUILDER_TAG=rhel-9-golang-1.25-openshift-4.21
ARG REGISTRY
ARG REPOSITORY=ubi9/ubi-minimal
ARG TAG=latest
FROM ${BUILDER_REGISTRY}/${BUILDER_REPOSITORY}:${BUILDER_TAG} AS builder

USER root
ENV GOPATH=/root/go
ENV GO_COMPLIANCE_INFO=0
RUN mkdir -p /app
WORKDIR /app

COPY . /app
RUN make proxy

FROM ${REGISTRY}/${REPOSITORY}:${TAG}
COPY --from=builder /app/proxy /usr/local/bin/
ENTRYPOINT ["proxy"]
EXPOSE 8443/tcp
EXPOSE 8080/tcp
USER 1000
