FROM registry.access.redhat.com/ubi8/nodejs-14
WORKDIR /data
USER root

COPY /portal/ /data/
RUN npm install -g

RUN set -eux \
	&& ln -sf /data/node_modules/eslint/bin/eslint.js /usr/bin/eslint

ENTRYPOINT ["eslint"]
CMD ["--help"]