# Uses a multi-stage container build to build the RP in OneBranch.
#
# TODO:
# OneBranch pipelines currently pull from CDPx which is deprecated. As a temporary fix before
# we migrate to a new solution, this multistage dockerfile uses the same image in both steps to avoid
# needing to pull images that aren't hosted in CDPx.
FROM cdpxlinux.azurecr.io/user/aro/ubi8-gotoolset-1.17.7-13:20220526 AS builder
ENV GOOS=linux \
    GOPATH=/go/
WORKDIR ${GOPATH}/src/github.com/Azure/ARO-RP
USER root
RUN yum update -y
COPY . ${GOPATH}/src/github.com/Azure/ARO-RP/
RUN make aro && make e2e.test

FROM cdpxlinux.azurecr.io/user/aro/ubi8-gotoolset-1.17.7-13:20220526
USER root
RUN yum -y update && yum -y clean all
COPY --from=builder /go/src/github.com/Azure/ARO-RP/aro /go/src/github.com/Azure/ARO-RP/e2e.test /usr/local/bin/
ENTRYPOINT ["aro"]
EXPOSE 2222/tcp 8080/tcp 8443/tcp 8444/tcp 8445/tcp
USER 1000
