# Uses a multi-stage container build to build the proxy
#
ARG REGISTRY
ARG BUILDER_REGISTRY
FROM ${BUILDER_REGISTRY}/openshift-release-dev/golang-builder--partner-share:rhel-9-golang-1.22-openshift-4.19 AS builder
USER root
ENV GOPATH=/root/go
RUN mkdir -p /app
WORKDIR /app

COPY . /app
RUN make proxy

FROM ${REGISTRY}/ubi9/ubi-minimal
RUN microdnf update && microdnf clean all
COPY --from=builder /app/proxy /usr/local/bin/
ENTRYPOINT ["proxy"]
EXPOSE 8443/tcp
EXPOSE 8080/tcp
USER 1000
