FROM registry.access.redhat.com/ubi8/ubi-minimal

USER root
RUN mkdir -p /app/ARO-RP
WORKDIR /app/ARO-RP

#we have multiple steps for copy so we can make use of caching
COPY . /app/ARO-RP

RUN microdnf update && \
    microdnf install make python39 git && \
    microdnf clean all
