# ignore everything
*

# ...except these
!.golangci.yml
!cmd
!go.mod
!go.sum
!hack
!pkg
!swagger
!test
!vendor

# Allow files and directories for JavaScript build
!portal/v2/package*.json
!portal/v2/src
!portal/v2/public
!portal/v2/config-overrides.js
!portal/v2/tsconfig.json
!portal/v2/.eslintrc.yml
!portal/v2/.npmrc

