ARG FEDORA_REGISTRY
FROM ${FEDORA_REGISTRY}/fedora:42

# Install system dependencies
RUN dnf update -y && dnf install -y \
    gpgme-devel \
    libassuan-devel \
    openssl \
    openssl-devel \
    openssl-libs \
    lvm2 \
    lvm2-devel \
    golang-github-containerd-btrfs-devel \
    bzip2-devel \
    ncurses-devel \
    libffi-devel \
    readline-devel \
    sqlite-devel \
    tk-devel \
    xz-devel \
    zlib-devel \
    gcc \
    make \
    patch \
    openvpn \
    podman \
    podman-docker \
    git \
    curl \
    wget \
    python3-pip \
    which \
    binutils-gold \
    && dnf clean all

WORKDIR /workspace

COPY go.mod go.mod
RUN GO_VERSION=$(awk '/^go / {print $2}' go.mod) && \
    ARCH=$(uname -m) && \
    case "$ARCH" in \
        x86_64) GO_ARCH=amd64 ;; \
        aarch64) GO_ARCH=arm64 ;; \
        *) echo "Unsupported architecture: $ARCH" && exit 1 ;; \
    esac && \
    wget -q "https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz" -O go.tar.gz && \
    tar -C /usr/local -xzf go.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"

RUN /usr/local/go/bin/go install github.com/bwplotka/bingo@latest
COPY .bingo/ .bingo/
RUN export PATH="/usr/local/go/bin:/root/go/bin:$PATH" && \
    /root/go/bin/bingo get
ENV PATH="/workspace/.bingo/bin:${PATH}"
