# Build container for POC usage
ARG REGISTRY
FROM ${REGISTRY}/ubi8/go-toolset:1.18.4 AS builder
ENV GOOS=linux \
    GOPATH=/go/
WORKDIR ${GOPATH}/src/github.com/Azure/ARO-RP
USER root
COPY . ${GOPATH}/src/github.com/Azure/ARO-RP/
RUN make aro

FROM ${REGISTRY}/ubi8/ubi-minimal
RUN microdnf update && microdnf clean all
COPY --from=builder /go/src/github.com/Azure/ARO-RP/aro /usr/local/bin/
ENTRYPOINT ["aro", "poc"]
USER 1000