// Code generated by "enumer -type Feature -output zz_generated_feature_enumer.go"; DO NOT EDIT.

package env

import (
	"fmt"
	"strings"
)

const _FeatureName = "FeatureDisableDenyAssignmentsFeatureDisableSignedCertificatesFeatureEnableDevelopmentAuthorizerFeatureDisableReadinessDelayFeatureRequireOIDCStorageWebEndpointFeatureUseMockMsiRpFeatureEnableMISEFeatureEnforceMISEFeatureEnableClusterExpandedAvailabilityZones"

var _FeatureIndex = [...]uint16{0, 29, 61, 95, 123, 159, 178, 195, 213, 258}

const _FeatureLowerName = "featuredisabledenyassignmentsfeaturedisablesignedcertificatesfeatureenabledevelopmentauthorizerfeaturedisablereadinessdelayfeaturerequireoidcstoragewebendpointfeatureusemockmsirpfeatureenablemisefeatureenforcemisefeatureenableclusterexpandedavailabilityzones"

func (i Feature) String() string {
	if i < 0 || i >= Feature(len(_FeatureIndex)-1) {
		return fmt.Sprintf("Feature(%d)", i)
	}
	return _FeatureName[_FeatureIndex[i]:_FeatureIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FeatureNoOp() {
	var x [1]struct{}
	_ = x[FeatureDisableDenyAssignments-(0)]
	_ = x[FeatureDisableSignedCertificates-(1)]
	_ = x[FeatureEnableDevelopmentAuthorizer-(2)]
	_ = x[FeatureDisableReadinessDelay-(3)]
	_ = x[FeatureRequireOIDCStorageWebEndpoint-(4)]
	_ = x[FeatureUseMockMsiRp-(5)]
	_ = x[FeatureEnableMISE-(6)]
	_ = x[FeatureEnforceMISE-(7)]
	_ = x[FeatureEnableClusterExpandedAvailabilityZones-(8)]
}

var _FeatureValues = []Feature{FeatureDisableDenyAssignments, FeatureDisableSignedCertificates, FeatureEnableDevelopmentAuthorizer, FeatureDisableReadinessDelay, FeatureRequireOIDCStorageWebEndpoint, FeatureUseMockMsiRp, FeatureEnableMISE, FeatureEnforceMISE, FeatureEnableClusterExpandedAvailabilityZones}

var _FeatureNameToValueMap = map[string]Feature{
	_FeatureName[0:29]:         FeatureDisableDenyAssignments,
	_FeatureLowerName[0:29]:    FeatureDisableDenyAssignments,
	_FeatureName[29:61]:        FeatureDisableSignedCertificates,
	_FeatureLowerName[29:61]:   FeatureDisableSignedCertificates,
	_FeatureName[61:95]:        FeatureEnableDevelopmentAuthorizer,
	_FeatureLowerName[61:95]:   FeatureEnableDevelopmentAuthorizer,
	_FeatureName[95:123]:       FeatureDisableReadinessDelay,
	_FeatureLowerName[95:123]:  FeatureDisableReadinessDelay,
	_FeatureName[123:159]:      FeatureRequireOIDCStorageWebEndpoint,
	_FeatureLowerName[123:159]: FeatureRequireOIDCStorageWebEndpoint,
	_FeatureName[159:178]:      FeatureUseMockMsiRp,
	_FeatureLowerName[159:178]: FeatureUseMockMsiRp,
	_FeatureName[178:195]:      FeatureEnableMISE,
	_FeatureLowerName[178:195]: FeatureEnableMISE,
	_FeatureName[195:213]:      FeatureEnforceMISE,
	_FeatureLowerName[195:213]: FeatureEnforceMISE,
	_FeatureName[213:258]:      FeatureEnableClusterExpandedAvailabilityZones,
	_FeatureLowerName[213:258]: FeatureEnableClusterExpandedAvailabilityZones,
}

var _FeatureNames = []string{
	_FeatureName[0:29],
	_FeatureName[29:61],
	_FeatureName[61:95],
	_FeatureName[95:123],
	_FeatureName[123:159],
	_FeatureName[159:178],
	_FeatureName[178:195],
	_FeatureName[195:213],
	_FeatureName[213:258],
}

// FeatureString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FeatureString(s string) (Feature, error) {
	if val, ok := _FeatureNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FeatureNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Feature values", s)
}

// FeatureValues returns all values of the enum
func FeatureValues() []Feature {
	return _FeatureValues
}

// FeatureStrings returns a slice of all String values of the enum
func FeatureStrings() []string {
	strs := make([]string, len(_FeatureNames))
	copy(strs, _FeatureNames)
	return strs
}

// IsAFeature returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Feature) IsAFeature() bool {
	for _, v := range _FeatureValues {
		if i == v {
			return true
		}
	}
	return false
}
