module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.3

retract (
	// Depends on retracted pdata v1.0.0-rc10 module, use v0.76.1
	v0.76.0
	// Release failed, use v0.69.1
	v0.69.0
	// Release failed, use v0.57.2
	v0.57.1
	// Release failed, use v0.57.2
	v0.57.0
)

require go.opentelemetry.io/collector/cmd/builder v0.153.0
