// Code generated by github.com/bennerv/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"context"
	"fmt"
	"net/http"
	"sync"

	"github.com/ugorji/go/codec"

	pkg "github.com/Azure/ARO-RP/pkg/api"
)

type (
	fakeMaintenanceScheduleDocumentTriggerHandler func(context.Context, *pkg.MaintenanceScheduleDocument) error
	fakeMaintenanceScheduleDocumentQueryHandler   func(MaintenanceScheduleDocumentClient, *Query, *Options) MaintenanceScheduleDocumentRawIterator
)

var _ MaintenanceScheduleDocumentClient = &FakeMaintenanceScheduleDocumentClient{}

// NewFakeMaintenanceScheduleDocumentClient returns a FakeMaintenanceScheduleDocumentClient
func NewFakeMaintenanceScheduleDocumentClient(h *codec.JsonHandle) *FakeMaintenanceScheduleDocumentClient {
	return &FakeMaintenanceScheduleDocumentClient{
		jsonHandle:                   h,
		maintenanceScheduleDocuments: make(map[string]*pkg.MaintenanceScheduleDocument),
		triggerHandlers:              make(map[string]fakeMaintenanceScheduleDocumentTriggerHandler),
		queryHandlers:                make(map[string]fakeMaintenanceScheduleDocumentQueryHandler),
	}
}

// FakeMaintenanceScheduleDocumentClient is a FakeMaintenanceScheduleDocumentClient
type FakeMaintenanceScheduleDocumentClient struct {
	lock                         sync.RWMutex
	jsonHandle                   *codec.JsonHandle
	maintenanceScheduleDocuments map[string]*pkg.MaintenanceScheduleDocument
	triggerHandlers              map[string]fakeMaintenanceScheduleDocumentTriggerHandler
	queryHandlers                map[string]fakeMaintenanceScheduleDocumentQueryHandler
	sorter                       func([]*pkg.MaintenanceScheduleDocument)
	etag                         int
	changeFeedIterators          []*fakeMaintenanceScheduleDocumentIterator

	// returns true if documents conflict
	conflictChecker func(*pkg.MaintenanceScheduleDocument, *pkg.MaintenanceScheduleDocument) bool

	// err, if not nil, is an error to return when attempting to communicate
	// with this Client
	err error
}

// SetError sets or unsets an error that will be returned on any
// FakeMaintenanceScheduleDocumentClient method invocation
func (c *FakeMaintenanceScheduleDocumentClient) SetError(err error) {
	c.lock.Lock()
	defer c.lock.Unlock()

	c.err = err
}

// SetSorter sets or unsets a sorter function which will be used to sort values
// returned by List() for test stability
func (c *FakeMaintenanceScheduleDocumentClient) SetSorter(sorter func([]*pkg.MaintenanceScheduleDocument)) {
	c.lock.Lock()
	defer c.lock.Unlock()

	c.sorter = sorter
}

// SetConflictChecker sets or unsets a function which can be used to validate
// additional unique keys in a MaintenanceScheduleDocument
func (c *FakeMaintenanceScheduleDocumentClient) SetConflictChecker(conflictChecker func(*pkg.MaintenanceScheduleDocument, *pkg.MaintenanceScheduleDocument) bool) {
	c.lock.Lock()
	defer c.lock.Unlock()

	c.conflictChecker = conflictChecker
}

// SetTriggerHandler sets or unsets a trigger handler
func (c *FakeMaintenanceScheduleDocumentClient) SetTriggerHandler(triggerName string, trigger fakeMaintenanceScheduleDocumentTriggerHandler) {
	c.lock.Lock()
	defer c.lock.Unlock()

	c.triggerHandlers[triggerName] = trigger
}

// SetQueryHandler sets or unsets a query handler
func (c *FakeMaintenanceScheduleDocumentClient) SetQueryHandler(queryName string, query fakeMaintenanceScheduleDocumentQueryHandler) {
	c.lock.Lock()
	defer c.lock.Unlock()

	c.queryHandlers[queryName] = query
}

func (c *FakeMaintenanceScheduleDocumentClient) deepCopy(maintenanceScheduleDocument *pkg.MaintenanceScheduleDocument) (*pkg.MaintenanceScheduleDocument, error) {
	var b []byte
	err := codec.NewEncoderBytes(&b, c.jsonHandle).Encode(maintenanceScheduleDocument)
	if err != nil {
		return nil, err
	}

	maintenanceScheduleDocument = nil
	err = codec.NewDecoderBytes(b, c.jsonHandle).Decode(&maintenanceScheduleDocument)
	if err != nil {
		return nil, err
	}

	return maintenanceScheduleDocument, nil
}

func (c *FakeMaintenanceScheduleDocumentClient) apply(ctx context.Context, partitionkey string, maintenanceScheduleDocument *pkg.MaintenanceScheduleDocument, options *Options, isCreate bool) (*pkg.MaintenanceScheduleDocument, error) {
	c.lock.Lock()
	defer c.lock.Unlock()

	if c.err != nil {
		return nil, c.err
	}

	maintenanceScheduleDocument, err := c.deepCopy(maintenanceScheduleDocument) // copy now because pretriggers can mutate maintenanceScheduleDocument
	if err != nil {
		return nil, err
	}

	if options != nil {
		err := c.processPreTriggers(ctx, maintenanceScheduleDocument, options)
		if err != nil {
			return nil, err
		}
	}

	existingMaintenanceScheduleDocument, exists := c.maintenanceScheduleDocuments[maintenanceScheduleDocument.ID]
	if isCreate && exists {
		return nil, &Error{
			StatusCode: http.StatusConflict,
			Message:    "Entity with the specified id already exists in the system",
		}
	}
	if !isCreate {
		if !exists {
			return nil, &Error{StatusCode: http.StatusNotFound}
		}

		if maintenanceScheduleDocument.ETag != existingMaintenanceScheduleDocument.ETag {
			return nil, &Error{StatusCode: http.StatusPreconditionFailed}
		}
	}

	if c.conflictChecker != nil {
		for _, maintenanceScheduleDocumentToCheck := range c.maintenanceScheduleDocuments {
			if c.conflictChecker(maintenanceScheduleDocumentToCheck, maintenanceScheduleDocument) {
				return nil, &Error{
					StatusCode: http.StatusConflict,
					Message:    "Entity with the specified id already exists in the system",
				}
			}
		}
	}

	maintenanceScheduleDocument.ETag = fmt.Sprint(c.etag)
	c.etag++

	c.maintenanceScheduleDocuments[maintenanceScheduleDocument.ID] = maintenanceScheduleDocument

	if err = c.updateChangeFeeds(maintenanceScheduleDocument); err != nil {
		return nil, err
	}

	return c.deepCopy(maintenanceScheduleDocument)
}

// Create creates a MaintenanceScheduleDocument in the database
func (c *FakeMaintenanceScheduleDocumentClient) Create(ctx context.Context, partitionkey string, maintenanceScheduleDocument *pkg.MaintenanceScheduleDocument, options *Options) (*pkg.MaintenanceScheduleDocument, error) {
	return c.apply(ctx, partitionkey, maintenanceScheduleDocument, options, true)
}

// Replace replaces a MaintenanceScheduleDocument in the database
func (c *FakeMaintenanceScheduleDocumentClient) Replace(ctx context.Context, partitionkey string, maintenanceScheduleDocument *pkg.MaintenanceScheduleDocument, options *Options) (*pkg.MaintenanceScheduleDocument, error) {
	return c.apply(ctx, partitionkey, maintenanceScheduleDocument, options, false)
}

// List returns a MaintenanceScheduleDocumentIterator to list all MaintenanceScheduleDocuments in the database
func (c *FakeMaintenanceScheduleDocumentClient) List(*Options) MaintenanceScheduleDocumentIterator {
	c.lock.RLock()
	defer c.lock.RUnlock()

	if c.err != nil {
		return NewFakeMaintenanceScheduleDocumentErroringRawIterator(c.err)
	}

	maintenanceScheduleDocuments := make([]*pkg.MaintenanceScheduleDocument, 0, len(c.maintenanceScheduleDocuments))
	for _, maintenanceScheduleDocument := range c.maintenanceScheduleDocuments {
		maintenanceScheduleDocument, err := c.deepCopy(maintenanceScheduleDocument)
		if err != nil {
			return NewFakeMaintenanceScheduleDocumentErroringRawIterator(err)
		}
		maintenanceScheduleDocuments = append(maintenanceScheduleDocuments, maintenanceScheduleDocument)
	}

	if c.sorter != nil {
		c.sorter(maintenanceScheduleDocuments)
	}

	return NewFakeMaintenanceScheduleDocumentIterator(maintenanceScheduleDocuments, 0)
}

// ListAll lists all MaintenanceScheduleDocuments in the database
func (c *FakeMaintenanceScheduleDocumentClient) ListAll(ctx context.Context, options *Options) (*pkg.MaintenanceScheduleDocuments, error) {
	iter := c.List(options)
	return iter.Next(ctx, -1)
}

// Get gets a MaintenanceScheduleDocument from the database
func (c *FakeMaintenanceScheduleDocumentClient) Get(ctx context.Context, partitionkey string, id string, options *Options) (*pkg.MaintenanceScheduleDocument, error) {
	c.lock.RLock()
	defer c.lock.RUnlock()

	if c.err != nil {
		return nil, c.err
	}

	maintenanceScheduleDocument, exists := c.maintenanceScheduleDocuments[id]
	if !exists {
		return nil, &Error{StatusCode: http.StatusNotFound}
	}

	return c.deepCopy(maintenanceScheduleDocument)
}

// Delete deletes a MaintenanceScheduleDocument from the database
func (c *FakeMaintenanceScheduleDocumentClient) Delete(ctx context.Context, partitionKey string, maintenanceScheduleDocument *pkg.MaintenanceScheduleDocument, options *Options) error {
	c.lock.Lock()
	defer c.lock.Unlock()

	if c.err != nil {
		return c.err
	}

	_, exists := c.maintenanceScheduleDocuments[maintenanceScheduleDocument.ID]
	if !exists {
		return &Error{StatusCode: http.StatusNotFound}
	}

	delete(c.maintenanceScheduleDocuments, maintenanceScheduleDocument.ID)
	return nil
}

// ChangeFeed is a basic implementation of cosmosDB Changefeeds. Compared to the real changefeeds, its implementation is much more simplistic:
// - Deleting a MaintenanceScheduleDocument does not remove it from the existing change feeds
// - when a MaintenanceScheduleDocument is pushed into the changefeed, older versions that have not been retrieved won't be removed, meaning there's no guarantee that a maintenanceScheduleDocument from the changefeed is actually the most recent version.
func (c *FakeMaintenanceScheduleDocumentClient) ChangeFeed(*Options) MaintenanceScheduleDocumentIterator {
	c.lock.RLock()
	defer c.lock.RUnlock()

	if c.err != nil {
		return NewFakeMaintenanceScheduleDocumentErroringRawIterator(c.err)
	}

	newIter, ok := c.List(nil).(*fakeMaintenanceScheduleDocumentIterator)
	if !ok {
		return NewFakeMaintenanceScheduleDocumentErroringRawIterator(fmt.Errorf("internal error"))
	}

	c.changeFeedIterators = append(c.changeFeedIterators, newIter)
	return newIter
}

func (c *FakeMaintenanceScheduleDocumentClient) updateChangeFeeds(maintenanceScheduleDocument *pkg.MaintenanceScheduleDocument) error {
	for _, currentIterator := range c.changeFeedIterators {
		newTpl, err := c.deepCopy(maintenanceScheduleDocument)
		if err != nil {
			return err
		}

		currentIterator.maintenanceScheduleDocuments = append(currentIterator.maintenanceScheduleDocuments, newTpl)
		currentIterator.done = false
	}
	return nil
}

func (c *FakeMaintenanceScheduleDocumentClient) processPreTriggers(ctx context.Context, maintenanceScheduleDocument *pkg.MaintenanceScheduleDocument, options *Options) error {
	for _, triggerName := range options.PreTriggers {
		if triggerHandler := c.triggerHandlers[triggerName]; triggerHandler != nil {
			c.lock.Unlock()
			err := triggerHandler(ctx, maintenanceScheduleDocument)
			c.lock.Lock()
			if err != nil {
				return err
			}
		} else {
			return ErrNotImplemented
		}
	}

	return nil
}

// Query calls a query handler to implement database querying
func (c *FakeMaintenanceScheduleDocumentClient) Query(name string, query *Query, options *Options) MaintenanceScheduleDocumentRawIterator {
	c.lock.RLock()
	defer c.lock.RUnlock()

	if c.err != nil {
		return NewFakeMaintenanceScheduleDocumentErroringRawIterator(c.err)
	}

	if queryHandler := c.queryHandlers[query.Query]; queryHandler != nil {
		c.lock.RUnlock()
		i := queryHandler(c, query, options)
		c.lock.RLock()
		return i
	}

	return NewFakeMaintenanceScheduleDocumentErroringRawIterator(ErrNotImplemented)
}

// QueryAll calls a query handler to implement database querying
func (c *FakeMaintenanceScheduleDocumentClient) QueryAll(ctx context.Context, partitionkey string, query *Query, options *Options) (*pkg.MaintenanceScheduleDocuments, error) {
	iter := c.Query("", query, options)
	return iter.Next(ctx, -1)
}

func NewFakeMaintenanceScheduleDocumentIterator(maintenanceScheduleDocuments []*pkg.MaintenanceScheduleDocument, continuation int) MaintenanceScheduleDocumentRawIterator {
	return &fakeMaintenanceScheduleDocumentIterator{maintenanceScheduleDocuments: maintenanceScheduleDocuments, continuation: continuation}
}

type fakeMaintenanceScheduleDocumentIterator struct {
	maintenanceScheduleDocuments []*pkg.MaintenanceScheduleDocument
	continuation                 int
	done                         bool
}

func (i *fakeMaintenanceScheduleDocumentIterator) NextRaw(ctx context.Context, maxItemCount int, out interface{}) error {
	return ErrNotImplemented
}

func (i *fakeMaintenanceScheduleDocumentIterator) Next(ctx context.Context, maxItemCount int) (*pkg.MaintenanceScheduleDocuments, error) {
	if i.done {
		return nil, nil
	}

	var maintenanceScheduleDocuments []*pkg.MaintenanceScheduleDocument
	if maxItemCount == -1 {
		maintenanceScheduleDocuments = i.maintenanceScheduleDocuments[i.continuation:]
		i.continuation = len(i.maintenanceScheduleDocuments)
		i.done = true
	} else {
		max := i.continuation + maxItemCount
		if max > len(i.maintenanceScheduleDocuments) {
			max = len(i.maintenanceScheduleDocuments)
		}
		maintenanceScheduleDocuments = i.maintenanceScheduleDocuments[i.continuation:max]
		i.continuation = max
		i.done = i.Continuation() == ""
	}

	return &pkg.MaintenanceScheduleDocuments{
		MaintenanceScheduleDocuments: maintenanceScheduleDocuments,
		Count:                        len(maintenanceScheduleDocuments),
	}, nil
}

func (i *fakeMaintenanceScheduleDocumentIterator) Continuation() string {
	if i.continuation >= len(i.maintenanceScheduleDocuments) {
		return ""
	}
	return fmt.Sprintf("%d", i.continuation)
}

// NewFakeMaintenanceScheduleDocumentErroringRawIterator returns a MaintenanceScheduleDocumentRawIterator which
// whose methods return the given error
func NewFakeMaintenanceScheduleDocumentErroringRawIterator(err error) MaintenanceScheduleDocumentRawIterator {
	return &fakeMaintenanceScheduleDocumentErroringRawIterator{err: err}
}

type fakeMaintenanceScheduleDocumentErroringRawIterator struct {
	err error
}

func (i *fakeMaintenanceScheduleDocumentErroringRawIterator) Next(ctx context.Context, maxItemCount int) (*pkg.MaintenanceScheduleDocuments, error) {
	return nil, i.err
}

func (i *fakeMaintenanceScheduleDocumentErroringRawIterator) NextRaw(context.Context, int, interface{}) error {
	return i.err
}

func (i *fakeMaintenanceScheduleDocumentErroringRawIterator) Continuation() string {
	return ""
}
