// Code generated by github.com/jewzaam/go-cosmosdb, DO NOT EDIT.

package cosmosdb

import (
	"context"
	"net/http"
	"strconv"
	"strings"

	pkg "github.com/Azure/ARO-RP/pkg/api"
)

type backendDocumentClient struct {
	*databaseClient
	path string
}

// BackendDocumentClient is a backendDocument client
type BackendDocumentClient interface {
	Create(context.Context, string, *pkg.BackendDocument, *Options) (*pkg.BackendDocument, error)
	List(*Options) BackendDocumentIterator
	ListAll(context.Context, *Options) (*pkg.BackendDocuments, error)
	Get(context.Context, string, string, *Options) (*pkg.BackendDocument, error)
	Replace(context.Context, string, *pkg.BackendDocument, *Options) (*pkg.BackendDocument, error)
	Delete(context.Context, string, *pkg.BackendDocument, *Options) error
	Query(string, *Query, *Options) BackendDocumentRawIterator
	QueryAll(context.Context, string, *Query, *Options) (*pkg.BackendDocuments, error)
	ChangeFeed(*Options) BackendDocumentIterator
}

type backendDocumentChangeFeedIterator struct {
	*backendDocumentClient
	continuation string
	options      *Options
}

type backendDocumentListIterator struct {
	*backendDocumentClient
	continuation string
	done         bool
	options      *Options
}

type backendDocumentQueryIterator struct {
	*backendDocumentClient
	partitionkey string
	query        *Query
	continuation string
	done         bool
	options      *Options
}

// BackendDocumentIterator is a backendDocument iterator
type BackendDocumentIterator interface {
	Next(context.Context, int) (*pkg.BackendDocuments, error)
	Continuation() string
}

// BackendDocumentRawIterator is a backendDocument raw iterator
type BackendDocumentRawIterator interface {
	BackendDocumentIterator
	NextRaw(context.Context, int, interface{}) error
}

// NewBackendDocumentClient returns a new backendDocument client
func NewBackendDocumentClient(collc CollectionClient, collid string) BackendDocumentClient {
	return &backendDocumentClient{
		databaseClient: collc.(*collectionClient).databaseClient,
		path:           collc.(*collectionClient).path + "/colls/" + collid,
	}
}

func (c *backendDocumentClient) all(ctx context.Context, i BackendDocumentIterator) (*pkg.BackendDocuments, error) {
	allbackendDocuments := &pkg.BackendDocuments{}

	for {
		backendDocuments, err := i.Next(ctx, -1)
		if err != nil {
			return nil, err
		}
		if backendDocuments == nil {
			break
		}

		allbackendDocuments.Count += backendDocuments.Count
		allbackendDocuments.ResourceID = backendDocuments.ResourceID
		allbackendDocuments.BackendDocuments = append(allbackendDocuments.BackendDocuments, backendDocuments.BackendDocuments...)
	}

	return allbackendDocuments, nil
}

func (c *backendDocumentClient) Create(ctx context.Context, partitionkey string, newbackendDocument *pkg.BackendDocument, options *Options) (backendDocument *pkg.BackendDocument, err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)

	if options == nil {
		options = &Options{}
	}
	options.NoETag = true

	err = c.setOptions(options, newbackendDocument, headers)
	if err != nil {
		return
	}

	err = c.do(ctx, http.MethodPost, c.path+"/docs", "docs", c.path, http.StatusCreated, &newbackendDocument, &backendDocument, headers)
	return
}

func (c *backendDocumentClient) List(options *Options) BackendDocumentIterator {
	continuation := ""
	if options != nil {
		continuation = options.Continuation
	}

	return &backendDocumentListIterator{backendDocumentClient: c, options: options, continuation: continuation}
}

func (c *backendDocumentClient) ListAll(ctx context.Context, options *Options) (*pkg.BackendDocuments, error) {
	return c.all(ctx, c.List(options))
}

func (c *backendDocumentClient) Get(ctx context.Context, partitionkey, backendDocumentid string, options *Options) (backendDocument *pkg.BackendDocument, err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)

	err = c.setOptions(options, nil, headers)
	if err != nil {
		return
	}

	err = c.do(ctx, http.MethodGet, c.path+"/docs/"+backendDocumentid, "docs", c.path+"/docs/"+backendDocumentid, http.StatusOK, nil, &backendDocument, headers)
	return
}

func (c *backendDocumentClient) Replace(ctx context.Context, partitionkey string, newbackendDocument *pkg.BackendDocument, options *Options) (backendDocument *pkg.BackendDocument, err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)

	err = c.setOptions(options, newbackendDocument, headers)
	if err != nil {
		return
	}

	err = c.do(ctx, http.MethodPut, c.path+"/docs/"+newbackendDocument.ID, "docs", c.path+"/docs/"+newbackendDocument.ID, http.StatusOK, &newbackendDocument, &backendDocument, headers)
	return
}

func (c *backendDocumentClient) Delete(ctx context.Context, partitionkey string, backendDocument *pkg.BackendDocument, options *Options) (err error) {
	headers := http.Header{}
	headers.Set("X-Ms-Documentdb-Partitionkey", `["`+partitionkey+`"]`)

	err = c.setOptions(options, backendDocument, headers)
	if err != nil {
		return
	}

	err = c.do(ctx, http.MethodDelete, c.path+"/docs/"+backendDocument.ID, "docs", c.path+"/docs/"+backendDocument.ID, http.StatusNoContent, nil, nil, headers)
	return
}

func (c *backendDocumentClient) Query(partitionkey string, query *Query, options *Options) BackendDocumentRawIterator {
	continuation := ""
	if options != nil {
		continuation = options.Continuation
	}

	return &backendDocumentQueryIterator{backendDocumentClient: c, partitionkey: partitionkey, query: query, options: options, continuation: continuation}
}

func (c *backendDocumentClient) QueryAll(ctx context.Context, partitionkey string, query *Query, options *Options) (*pkg.BackendDocuments, error) {
	return c.all(ctx, c.Query(partitionkey, query, options))
}

func (c *backendDocumentClient) ChangeFeed(options *Options) BackendDocumentIterator {
	continuation := ""
	if options != nil {
		continuation = options.Continuation
	}

	return &backendDocumentChangeFeedIterator{backendDocumentClient: c, options: options, continuation: continuation}
}

func (c *backendDocumentClient) setOptions(options *Options, backendDocument *pkg.BackendDocument, headers http.Header) error {
	if options == nil {
		return nil
	}

	if backendDocument != nil && !options.NoETag {
		if backendDocument.ETag == "" {
			return ErrETagRequired
		}
		headers.Set("If-Match", backendDocument.ETag)
	}
	if len(options.PreTriggers) > 0 {
		headers.Set("X-Ms-Documentdb-Pre-Trigger-Include", strings.Join(options.PreTriggers, ","))
	}
	if len(options.PostTriggers) > 0 {
		headers.Set("X-Ms-Documentdb-Post-Trigger-Include", strings.Join(options.PostTriggers, ","))
	}
	if len(options.PartitionKeyRangeID) > 0 {
		headers.Set("X-Ms-Documentdb-PartitionKeyRangeID", options.PartitionKeyRangeID)
	}

	return nil
}

func (i *backendDocumentChangeFeedIterator) Next(ctx context.Context, maxItemCount int) (backendDocuments *pkg.BackendDocuments, err error) {
	headers := http.Header{}
	headers.Set("A-IM", "Incremental feed")

	headers.Set("X-Ms-Max-Item-Count", strconv.Itoa(maxItemCount))
	if i.continuation != "" {
		headers.Set("If-None-Match", i.continuation)
	}

	err = i.setOptions(i.options, nil, headers)
	if err != nil {
		return
	}

	err = i.do(ctx, http.MethodGet, i.path+"/docs", "docs", i.path, http.StatusOK, nil, &backendDocuments, headers)
	if IsErrorStatusCode(err, http.StatusNotModified) {
		err = nil
	}
	if err != nil {
		return
	}

	i.continuation = headers.Get("Etag")

	return
}

func (i *backendDocumentChangeFeedIterator) Continuation() string {
	return i.continuation
}

func (i *backendDocumentListIterator) Next(ctx context.Context, maxItemCount int) (backendDocuments *pkg.BackendDocuments, err error) {
	if i.done {
		return
	}

	headers := http.Header{}
	headers.Set("X-Ms-Max-Item-Count", strconv.Itoa(maxItemCount))
	if i.continuation != "" {
		headers.Set("X-Ms-Continuation", i.continuation)
	}

	err = i.setOptions(i.options, nil, headers)
	if err != nil {
		return
	}

	err = i.do(ctx, http.MethodGet, i.path+"/docs", "docs", i.path, http.StatusOK, nil, &backendDocuments, headers)
	if err != nil {
		return
	}

	i.continuation = headers.Get("X-Ms-Continuation")
	i.done = i.continuation == ""

	return
}

func (i *backendDocumentListIterator) Continuation() string {
	return i.continuation
}

func (i *backendDocumentQueryIterator) Next(ctx context.Context, maxItemCount int) (backendDocuments *pkg.BackendDocuments, err error) {
	err = i.NextRaw(ctx, maxItemCount, &backendDocuments)
	return
}

func (i *backendDocumentQueryIterator) NextRaw(ctx context.Context, maxItemCount int, raw interface{}) (err error) {
	if i.done {
		return
	}

	headers := http.Header{}
	headers.Set("X-Ms-Max-Item-Count", strconv.Itoa(maxItemCount))
	headers.Set("X-Ms-Documentdb-Isquery", "True")
	headers.Set("Content-Type", "application/query+json")
	if i.partitionkey != "" {
		headers.Set("X-Ms-Documentdb-Partitionkey", `["`+i.partitionkey+`"]`)
	} else {
		headers.Set("X-Ms-Documentdb-Query-Enablecrosspartition", "True")
	}
	if i.continuation != "" {
		headers.Set("X-Ms-Continuation", i.continuation)
	}

	err = i.setOptions(i.options, nil, headers)
	if err != nil {
		return
	}

	err = i.do(ctx, http.MethodPost, i.path+"/docs", "docs", i.path, http.StatusOK, &i.query, &raw, headers)
	if err != nil {
		return
	}

	i.continuation = headers.Get("X-Ms-Continuation")
	i.done = i.continuation == ""

	return
}

func (i *backendDocumentQueryIterator) Continuation() string {
	return i.continuation
}
