#!/usr/bin/env bash
set -e
LC_ALL=C

git_username_lower="$(git config github.user | tr '[:upper:]' '[:lower:]')"
if [[ -z "${git_username_lower}" ]]
then
    echo "Please set github.user (git config github.user) locally or globally before issuing commits to this repo."
    exit 1
fi

# e.g. "USERNAME/ARO-1234", "USERNAME/hotfix-v20240321.00", or "USERNAME/gh-issue-123"
valid_branch_regex="^${git_username_lower}\/(ARO-[0-9]{4}[a-z0-9._-]*|hotfix-[a-z0-9._-]+|gh-issue-[0-9]+[a-z0-9._-]*)$"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. Please rename your branch (git branch --move) to a valid name and try again."
    exit 1
fi

exit 0