#!/usr/bin/env bash
set -e
LC_ALL=C

echo "Before pushing commits, ensure you've run the required make commands:"
echo "  - make generate"
echo "  - make imports"
read -r -p "Have you run all required make commands? [y/N] " run_make_commands
if [[ ! "${run_make_commands}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo "Commit aborted. Run the required make commands and try again."
    exit 1
fi

exit 0
