// Code generated by MockGen. DO NOT EDIT.
// Source: ./user_assigned_identities.go
//
// Generated by this command:
//
//	mockgen -source ./user_assigned_identities.go -destination=../../../mocks/azureclient/azuresdk/armmsi/user_assigned_identities.go github.com/Azure/ARO-RP/pkg/util/azureclient/azuresdk/armmsi UserAssignedIdentitiesClient
//

// Package mock_armmsi is a generated GoMock package.
package mock_armmsi

import (
	context "context"
	reflect "reflect"

	armmsi "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi"
	gomock "go.uber.org/mock/gomock"

	azcore "github.com/Azure/ARO-RP/pkg/util/azureclient/azuresdk/azcore"
)

// MockUserAssignedIdentitiesClient is a mock of UserAssignedIdentitiesClient interface.
type MockUserAssignedIdentitiesClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserAssignedIdentitiesClientMockRecorder
	isgomock struct{}
}

// MockUserAssignedIdentitiesClientMockRecorder is the mock recorder for MockUserAssignedIdentitiesClient.
type MockUserAssignedIdentitiesClientMockRecorder struct {
	mock *MockUserAssignedIdentitiesClient
}

// NewMockUserAssignedIdentitiesClient creates a new mock instance.
func NewMockUserAssignedIdentitiesClient(ctrl *gomock.Controller) *MockUserAssignedIdentitiesClient {
	mock := &MockUserAssignedIdentitiesClient{ctrl: ctrl}
	mock.recorder = &MockUserAssignedIdentitiesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAssignedIdentitiesClient) EXPECT() *MockUserAssignedIdentitiesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserAssignedIdentitiesClient) Get(ctx context.Context, resourceGroupName, resourceName string, options *armmsi.UserAssignedIdentitiesClientGetOptions) (armmsi.UserAssignedIdentitiesClientGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, resourceName, options)
	ret0, _ := ret[0].(armmsi.UserAssignedIdentitiesClientGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserAssignedIdentitiesClientMockRecorder) Get(ctx, resourceGroupName, resourceName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserAssignedIdentitiesClient)(nil).Get), ctx, resourceGroupName, resourceName, options)
}

// GetClusterMSICredential mocks base method.
func (m *MockUserAssignedIdentitiesClient) GetClusterMSICredential() azcore.TokenCredential {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterMSICredential")
	ret0, _ := ret[0].(azcore.TokenCredential)
	return ret0
}

// GetClusterMSICredential indicates an expected call of GetClusterMSICredential.
func (mr *MockUserAssignedIdentitiesClientMockRecorder) GetClusterMSICredential() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterMSICredential", reflect.TypeOf((*MockUserAssignedIdentitiesClient)(nil).GetClusterMSICredential))
}
