// Code generated by MockGen. DO NOT EDIT.
// Source: dynamic.go
//
// Generated by this command:
//
//	mockgen -destination=../../../pkg/util/mocks/dynamic/dynamic.go -source=dynamic.go
//

// Package mock_dynamic is a generated GoMock package.
package mock_dynamic

import (
	context "context"
	reflect "reflect"

	azcore "github.com/Azure/azure-sdk-for-go/sdk/azcore"
	gomock "go.uber.org/mock/gomock"

	api "github.com/Azure/ARO-RP/pkg/api"
	armauthorization "github.com/Azure/ARO-RP/pkg/util/azureclient/azuresdk/armauthorization"
	armmsi "github.com/Azure/ARO-RP/pkg/util/azureclient/azuresdk/armmsi"
	dynamic "github.com/Azure/ARO-RP/pkg/validate/dynamic"
)

// MockServicePrincipalValidator is a mock of ServicePrincipalValidator interface.
type MockServicePrincipalValidator struct {
	ctrl     *gomock.Controller
	recorder *MockServicePrincipalValidatorMockRecorder
	isgomock struct{}
}

// MockServicePrincipalValidatorMockRecorder is the mock recorder for MockServicePrincipalValidator.
type MockServicePrincipalValidatorMockRecorder struct {
	mock *MockServicePrincipalValidator
}

// NewMockServicePrincipalValidator creates a new mock instance.
func NewMockServicePrincipalValidator(ctrl *gomock.Controller) *MockServicePrincipalValidator {
	mock := &MockServicePrincipalValidator{ctrl: ctrl}
	mock.recorder = &MockServicePrincipalValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicePrincipalValidator) EXPECT() *MockServicePrincipalValidatorMockRecorder {
	return m.recorder
}

// ValidateServicePrincipal mocks base method.
func (m *MockServicePrincipalValidator) ValidateServicePrincipal(ctx context.Context, spTokenCredential azcore.TokenCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateServicePrincipal", ctx, spTokenCredential)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateServicePrincipal indicates an expected call of ValidateServicePrincipal.
func (mr *MockServicePrincipalValidatorMockRecorder) ValidateServicePrincipal(ctx, spTokenCredential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateServicePrincipal", reflect.TypeOf((*MockServicePrincipalValidator)(nil).ValidateServicePrincipal), ctx, spTokenCredential)
}

// MockDynamic is a mock of Dynamic interface.
type MockDynamic struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicMockRecorder
	isgomock struct{}
}

// MockDynamicMockRecorder is the mock recorder for MockDynamic.
type MockDynamicMockRecorder struct {
	mock *MockDynamic
}

// NewMockDynamic creates a new mock instance.
func NewMockDynamic(ctrl *gomock.Controller) *MockDynamic {
	mock := &MockDynamic{ctrl: ctrl}
	mock.recorder = &MockDynamicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamic) EXPECT() *MockDynamicMockRecorder {
	return m.recorder
}

// ValidateClusterUserAssignedIdentity mocks base method.
func (m *MockDynamic) ValidateClusterUserAssignedIdentity(ctx context.Context, platformIdentities map[string]api.PlatformWorkloadIdentity, roleDefinitions armauthorization.RoleDefinitionsClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateClusterUserAssignedIdentity", ctx, platformIdentities, roleDefinitions)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateClusterUserAssignedIdentity indicates an expected call of ValidateClusterUserAssignedIdentity.
func (mr *MockDynamicMockRecorder) ValidateClusterUserAssignedIdentity(ctx, platformIdentities, roleDefinitions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateClusterUserAssignedIdentity", reflect.TypeOf((*MockDynamic)(nil).ValidateClusterUserAssignedIdentity), ctx, platformIdentities, roleDefinitions)
}

// ValidateDiskEncryptionSets mocks base method.
func (m *MockDynamic) ValidateDiskEncryptionSets(ctx context.Context, oc *api.OpenShiftCluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDiskEncryptionSets", ctx, oc)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateDiskEncryptionSets indicates an expected call of ValidateDiskEncryptionSets.
func (mr *MockDynamicMockRecorder) ValidateDiskEncryptionSets(ctx, oc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDiskEncryptionSets", reflect.TypeOf((*MockDynamic)(nil).ValidateDiskEncryptionSets), ctx, oc)
}

// ValidateLoadBalancerProfile mocks base method.
func (m *MockDynamic) ValidateLoadBalancerProfile(ctx context.Context, oc *api.OpenShiftCluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLoadBalancerProfile", ctx, oc)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateLoadBalancerProfile indicates an expected call of ValidateLoadBalancerProfile.
func (mr *MockDynamicMockRecorder) ValidateLoadBalancerProfile(ctx, oc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLoadBalancerProfile", reflect.TypeOf((*MockDynamic)(nil).ValidateLoadBalancerProfile), ctx, oc)
}

// ValidatePlatformWorkloadIdentityProfile mocks base method.
func (m *MockDynamic) ValidatePlatformWorkloadIdentityProfile(ctx context.Context, oc *api.OpenShiftCluster, platformWorkloadIdentityRolesByRoleName map[string]api.PlatformWorkloadIdentityRole, roleDefinitions armauthorization.RoleDefinitionsClient, clusterMsiFederatedIdentityCredentials armmsi.FederatedIdentityCredentialsClient, platformWorkloadIdentities map[string]api.PlatformWorkloadIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePlatformWorkloadIdentityProfile", ctx, oc, platformWorkloadIdentityRolesByRoleName, roleDefinitions, clusterMsiFederatedIdentityCredentials, platformWorkloadIdentities)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePlatformWorkloadIdentityProfile indicates an expected call of ValidatePlatformWorkloadIdentityProfile.
func (mr *MockDynamicMockRecorder) ValidatePlatformWorkloadIdentityProfile(ctx, oc, platformWorkloadIdentityRolesByRoleName, roleDefinitions, clusterMsiFederatedIdentityCredentials, platformWorkloadIdentities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePlatformWorkloadIdentityProfile", reflect.TypeOf((*MockDynamic)(nil).ValidatePlatformWorkloadIdentityProfile), ctx, oc, platformWorkloadIdentityRolesByRoleName, roleDefinitions, clusterMsiFederatedIdentityCredentials, platformWorkloadIdentities)
}

// ValidatePreConfiguredNSGs mocks base method.
func (m *MockDynamic) ValidatePreConfiguredNSGs(ctx context.Context, oc *api.OpenShiftCluster, subnets []dynamic.Subnet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePreConfiguredNSGs", ctx, oc, subnets)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePreConfiguredNSGs indicates an expected call of ValidatePreConfiguredNSGs.
func (mr *MockDynamicMockRecorder) ValidatePreConfiguredNSGs(ctx, oc, subnets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePreConfiguredNSGs", reflect.TypeOf((*MockDynamic)(nil).ValidatePreConfiguredNSGs), ctx, oc, subnets)
}

// ValidateServicePrincipal mocks base method.
func (m *MockDynamic) ValidateServicePrincipal(ctx context.Context, spTokenCredential azcore.TokenCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateServicePrincipal", ctx, spTokenCredential)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateServicePrincipal indicates an expected call of ValidateServicePrincipal.
func (mr *MockDynamicMockRecorder) ValidateServicePrincipal(ctx, spTokenCredential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateServicePrincipal", reflect.TypeOf((*MockDynamic)(nil).ValidateServicePrincipal), ctx, spTokenCredential)
}

// ValidateSubnets mocks base method.
func (m *MockDynamic) ValidateSubnets(ctx context.Context, oc *api.OpenShiftCluster, subnets []dynamic.Subnet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSubnets", ctx, oc, subnets)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSubnets indicates an expected call of ValidateSubnets.
func (mr *MockDynamicMockRecorder) ValidateSubnets(ctx, oc, subnets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSubnets", reflect.TypeOf((*MockDynamic)(nil).ValidateSubnets), ctx, oc, subnets)
}

// ValidateVnet mocks base method.
func (m *MockDynamic) ValidateVnet(ctx context.Context, location string, subnets []dynamic.Subnet, additionalCIDRs ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, location, subnets}
	for _, a := range additionalCIDRs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidateVnet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateVnet indicates an expected call of ValidateVnet.
func (mr *MockDynamicMockRecorder) ValidateVnet(ctx, location, subnets any, additionalCIDRs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, location, subnets}, additionalCIDRs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateVnet", reflect.TypeOf((*MockDynamic)(nil).ValidateVnet), varargs...)
}
