name: ci-bash

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  bash-unit-tests:
    name: bash-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run bash unit tests
        run: make unit-test-bash
