---
# MegaLinter GitHub Action configuration file
# More info at https://oxsecurity.github.io/megalinter
name: mega-linter-yaml

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: mega-linter-yaml
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: yamllint
      uses: oxsecurity/megalinter/flavors/ci_light@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0
